version: '3'

services:
  mkdocs:
    container_name: mkdocs
    build: .
    restart: always
    command: serve --dev-addr=0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - "${PWD}:/docs"