site_name: Usertune Docs
site_url: https://docs.usertune.io
site_description: Usertune is a dynamic content personalization platform that delivers tailored experiences to users based on real-time context and behavior.
site_author: omegion

edit_uri: https://github.com/usertune/docs/blob/main/docs/

docs_dir: docs
site_dir: site
copyright: <script>document.write(new Date().getFullYear())</script> &copy; <a href="https://usertune.io" target="_blank">Usertune</a> &bull; Made with ❤️ in Berlin

nav:
  - Home: index.md
  - Workspace: 
    - Overview: workspace/index.md
    - Getting Started: workspace/getting-started.md
    - Public Workspaces: workspace/public-workspaces.md
  - Content:
    - Overview: content/index.md
    - Getting Started: content/getting-started.md
    - Public Content: content/public-content.md
  - Variant:
    - Overview: variant/index.md
    - Getting Started: variant/getting-started.md
    - Payload: variant/payload.md
    - Conditions: variant/conditions.md
    - Geographic Attributes: variant/geo-attributes.md
    - Time Attributes: variant/time-attributes.md
    - Custom Attributes: variant/custom-attributes.md
  - Libraries:
    - Overview: libraries/index.md
    - JavaScript: libraries/javascript.md
  - Legal & Compliance:
    - Overview: legal/index.md
    - Geographical Restrictions: legal/geographical-restrictions.md
  - Testing:
    - Overview: testing/index.md
    - Getting Started: testing/getting-started.md
    - Context Configuration: testing/context-configuration.md
    - Test Scenarios: testing/scenarios.md
    - Best Practices: testing/best-practices.md
    - API Testing: testing/api-testing.md

theme:
  name: material
  logo: assets/img/logo.png
  favicon: assets/favicons/favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.footer
    - toc.follow
    - content.tooltips
    - search.suggest
    - search.highlight
extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/usertune
      name: Github Profile of Usertune
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: usertune/docs
      branch: main
      token: !ENV ["GITHUB_TOKEN"]